name: Application Build 🏗️ 
run-name: ${{ github.actor }} is executing the workflow ${{ github.workflow }}.

on: [push]

jobs:
  build:
    name: build
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          ./scripts/check_env.sh
          ./scripts/run.sh "build -x test --no-daemon" "${{ github.job }}/${{ github.step }}"

  test:
    name: test
    needs: build
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: |
          ./scripts/check_env.sh
          ./scripts/run.sh "test --no-daemon" "${{ github.job }}/${{ github.step }}"

  publication:
    name: apk_distribution 
    needs: build    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Assemble
        working-directory: ${{ github.workspace }}
        run: ./scripts/run.sh "assembleRelease --no-daemon" "${{ github.job }}/${{ github.step }}"
        
      - name: Upload APK
        run: ./scripts/publish.sh ${{ github.sha }}
      
  code_linting:
    name: code_analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: PMD analysis
        uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          sourcePath: 'app/src/main/java'
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
          createGitHubAnnotations: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
