name: application build
run-name: ${{ github.actor }} is building an application.

on: [push]

jobs:
  build:
    name: build
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          ./scripts/check_env.sh
          ./gradlew build -x test

  test:
    name: test
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: ./gradlew test

  export:
    name: distribute_apk
    needs: build    
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload APK 
        working-directory: ${{ github.workspace }}
        run: |
          ./gradlew assembleRelease
          echo "APK download URL" $(curl --upload-file app/build/outputs/apk/release/*.apk https://transfer.sh/hermes.apk)
