name: application build
run-name: ${{ github.actor }} is building an application.

on: [push]

jobs:
  env_present:
    name: check_if_environment_is_present
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "================================================== Checking Environment =================================================="
      - run: echo "================================================== SUCCESS =================================================="

  build:
    name: build
    needs: env_present
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        working-directory: ${{ github.workspace }}
        run: ./gradlew build -x test
      - run: echo "================================================== SUCCESS =================================================="

  test:
    name: test
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: ./gradlew test
      - run: echo "================================================== SUCCESS =================================================="

  export:
    name: distribute_apk
    needs: test    
    runs-on: self-hosted 
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "================================================== APK Distribution =================================================="
      - run: echo "================================================== SUCCESS =================================================="
